// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnkhwdjgxxcjjxsnixxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNua2h3ZGpneHhjamp4c25peHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTE4OTMsImV4cCI6MjA1ODM2Nzg5M30.wqj0mhUOBt_OP7lxU63Unnqbl6dQCKXnr1zRq7f0p_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);